config/routes.rb
Rails.application.routes.draw do

  get 'reports/show'

  get 'reports/index'

  get 'reports/new'

  get 'reports/edit'

  get 'reports/create'

  get 'reports/update'

  get 'reports/destroy'

  get 'reports/registrados'

  get 'reports/ganancias'

  get 'counts/index'

  get 'counts/show'

  get 'counts/new'

  get 'counts/edit'

  get 'counts/create'

  get 'counts/update'

  get 'counts/destroy'

  get 'couches/index'

  get 'couches/show'

  get 'couches/new'

  get 'couches/edit'

  get 'couches/create'

  get 'couches/update'

  get 'couches/destroy'

  get 'reserves/index'

  get 'reserves/show'

  get 'reserves/new'

  get 'reserves/edit'

  get 'reserves/create'

  get 'reserves/update'

  get 'reserves/destroy'

  get 'posters/show'

  

  resources :tipocouches
  resources :reserves
  resources :couches do
   get 'mis_couches', on: :collection 
  end
  resources :counts

  devise_for :users
  get 'welcome/index'

   root 'welcome#index'

end

app/models/couch.rb
class Couch < ActiveRecord::Base
	validates_presence_of :name		
	validates_presence_of :description		
	validates_presence_of :imageurl		
	validates_presence_of :tipocouch_id
	validates_presence_of :capacidad		
	validates_presence_of :localidad		

	belongs_to :tipocouch
	belongs_to :user
	belongs_to :count
	has_many :reserves
end

app/models/count.rb
class Count < ActiveRecord::Base

	validates_presence_of :dni 
	validates_presence_of :numtarj 
	validates_presence_of :venc 
	validates_presence_of :cod
	
	belongs_to :user
	has_many :couches
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
	validates_presence_of :name	
	validates_presence_of :fechaini
	validates_presence_of :fechafin
	validates_uniqueness_of :fechafin	
	
	validates_presence_of :couch_id
	
	belongs_to :couch
	belongs_to :user

	scope :confirmed, -> { where(confirmed: true) }	
end

app/models/tipocouch.rb
class Tipocouch < ActiveRecord::Base
	#attr_accessible  :name
	#sattr_accessible  :description
	validates_presence_of :name
	validates_uniqueness_of :name
	#default_scope -> {order("id_at_desc")}
	validates :name, presence: true, length: { minimum: 4 }
	has_many :couches
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	

	validates :name, presence: true, length: { minimum: 3 }
	validates :lastname, presence: true, length: { minimum: 3 }
	validates :provincia, presence: true, length: { minimum: 3 }
	validates :localidad, presence: true, length: { minimum: 3 }
  #validates :genero, presence: true

	validates :dni, presence: true, uniqueness: true, length: {is: 8}
	validates_numericality_of :dni, :message => "Debe ingresar numeros"



  has_many :couches
  has_many :counts

  has_many :reserves
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :current_password, :localidad, :provincia, :lastname, :dni, :genero) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :localidad, :provincia, :lastname, :dni, :premium, :precio_premium, :fecha_premium, :genero) }
        end

end

app/controllers/couches_controller.rb
class CouchesController < ApplicationController
 before_action :get_couch, only: [:edit, :update, :destroy]

  def get_couch
    @couch = Couch.find(params[:id])
  end

  def index
    @couch= Couch.all
  end

  def mis_couches
    @couches = current_user.couches
    current_user.premium = false
  end 

  def show    
    @couch = Couch.find(params[:id])
    @user = @couch.user
  end

  def new
    @couch = Couch.new
    @c = Couch.all 
    @t = Tipocouch.all  
    
  end

  def edit
  end

  def create
    @couch = Couch.new(params.require(:couch).permit(:name, :description, :imageurl, :localidad , :capacidad ,:tipocouch_id)) 
    @couch.user = current_user
    @couch.save

    redirect_to couches_path
  end

  def update
    @couch.update_attributes(params.require(:couch).permit(:name, :description, :imageurl, :tipocouch_id , :capacidad , :localidad))
     redirect_to couches_path
  end

  def destroy
    @couch.destroy
    redirect_to couches_path
  end
  

end

app/controllers/counts_controller.rb
class CountsController < ApplicationController
  before_action :get_count, only: [:edit, :update, :destroy]

  def get_count
    @count = Count.find(params[:id])
  end

  def index
    @count= Count.all
     @soy_premium=false
  end

  def show    
    @count = Count.find(params[:id])
    @user = @couch.user
  end

  def new
    @count = Count.new
    
        
  end

  def edit
  end

  def create
    @count = Count.new(params.require(:count).permit(:dni, :numtarj, :venc, :cod)) 
    @count.user = current_user
    @count.save

    redirect_to counts_path
  end

  def update
    @count.update_attributes(params.require(:count).permit(:dni, :numtarj, :venc, :cod))
     redirect_to counts_path
  end

  def destroy
    @count.destroy
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  
  def show
  	@estoy_en_vista=true
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def registrados
    @report = Report.all
    fe_ini=params[:fecha_inicio]
    fe_fin=params[:fecha_fin]
    @usuarios= User.where("created_at > ? AND  created_at < ?", fe_ini, fe_fin).order("created_at")
  end

  def ganancias
    @report = Report.all
    @usuarios = User.all
    #@usuarios= User.where("created_at > ? AND  created_at < ?", f_inicio, f_fin).order("created_at")
    @usuarios.each do |u|
      @total = @total + u.precio_premium
    end
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :get_reserve, only: [:edit, :update, :destroy]

  def get_reserve
    @reserve = Reserve.find(params[:id])
  end
  def index
     @reserve= Reserve.all
  end

  def show  
  @reserve = Reserve.find(params[:id])
    @user = @reserve.user  
  end

  def new
      @reserve = Reserve.new(couch_id: params[:couch_id])
  end

  def edit
  end

  def create
    @reserve = Reserve.new(params.require(:reserve).permit(:name, :fechaini, :fechafin, :couch_id ))
    @reserve.save

    redirect_to reserves_path
  end

  def update
     @reserve.update_attributes(params.require(:reserve).permit(:name, :fechaini, :fechafin, :confirmada, :couch_id , :user_id))
     redirect_to reserves_path
  end

  def destroy
    @reserve.destroy
    redirect_to reserves_path
  end
  
end

app/controllers/tipocouches_controller.rb
class TipocouchesController < ApplicationController
  before_action :get_tipocouch, only: [:edit, :update, :destroy, :show]

  def get_tipocouch
    @tipocouch = Tipocouch.find(params[:id])
  end

  def show
  end

  def index
    @tipocouches = Tipocouch.all.order(:id)
  end

  def new
    @tipocouch = Tipocouch.new
  end

  def edit

  end
 
  def create
    @tipocouch = Tipocouch.new(params.require(:tipocouch).permit(:name, :description))
    if @tipocouch.save
      redirect_to tipocouches_path
    else
      render 'new'
    end
  end

  def update
     if @tipocouch.update_attributes(params.require(:tipocouch).permit(:name, :description))
      redirect_to tipocouches_path
    else
     render 'edit'
    end
  end

  def destroy
    @tipocouch.destroy
    redirect_to tipocouches_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couches_helper.rb
module CouchesHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/tipocouches_helper.rb
module TipocouchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/couches/destroy.html.erb
<h1>Couches#destroy</h1>
<p>Find me in app/views/couches/destroy.html.erb</p>

app/views/couches/edit.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<label for=“name"> <font face="arial" size="5" color="green"> Ingrese los datos a modificar </font> </label>
 
 		<p  


		/p>


		<%= form_for(@couch) do |f| %> 
			<% if @couch.errors.any? %>
  				<div id="error_explanation">
    				<h2><%= pluralize(@couch.errors.count, "error") %> No se han guardado los cambios:</h2>
    				<ul>
    					<% @couch.errors.full_messages.each do |msg| %>
      						<li><%= msg %></li>
    					<% end %>
    				</ul>
 				 </div>
  			<% end %>
			
			<p>
				<%= f.label :name, 'Nombre del couch' %>
				<%= f.text_field :name %>
			</p>
			
			<p>
				<%= f.label :description, 'Descripcion del couch' %>
				<%= f.text_field :description %>
			</p>

			<p>
				<%= f.label :localidad, 'Localidad del couch' %>
				<%= f.text_field :localidad %>
			</p>
		
            <p>
				<%= f.label :capacidad, 'Capacidad del couch' %>
				<%= f.text_field :capacidad %>
			</p>

		<%= f.submit 'Guardar' %>

    	<% end %> 

		</p> 
 

		<p>

			<p> <%= link_to "Volver", href="/welcome/index" %> </p>

		</p> 


	</div>
	
</div> 

app/views/couches/index.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<td><P ALIGN=right>
                   <a class="btn btn-primary btn-lg" href="/couches/new" role=“button"> Conviértete en anfitrión </a>
         <P ALIGN=left>         
		<label for=“name"> <font face="arial" size="5" color="green"> A continuacion se encuentra el listado de los couchs  </font> </label> 


	
		<p>

		</p>  
  	
  		<table class="table">
  			
 			<tr>
 				
				<th> <label for=“name"> <font face="arial" size="4" color="green">  Nombre del couch </font> </label> </th>
				
				<th> <label for=“name"> <font face="arial" size="4" color="green">  Imagen del couch </font> </label> </th>


			</tr>

			  <% @couch.each do |c| %>

				<tr> 
					
                    <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= c.name %> </font> </label></td>                
                    					
				 
                    
					 <td> <%= link_to couch_path(id: c.id) do %> <%= image_tag c.imageurl, size: '350x250' %> <% end %> </td>

                      <td> <%= link_to new_reserf_path(id: c.id) do %> Solicitar reserva <% end %> </td>
				</tr> 
	         
			<% end %>

		</table>

		<p>
			<a class="btn btn-primary btn-lg" href="/welcome/index" role=“button"> Volver </a>
		</p> 


	</div>
	
</div>

app/views/couches/mis_couches.html.erb

<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		  
		<label for="name"> <font face="arial" size="5" color="green"> A continuacion se encuentra el listado de tus couches  </font> </label> 	
		<p>

		</p>  
  	
  		<table class="table">
            
             <tr>
 				
				<th> <label for=“name"> <font face="arial" size="4" color="green">  Nombre del couch </font> </label> </th>  

				<th> <label for=“name"> <font face="arial" size="4" color="green">  Descripcion de mi couch </font> </label> </th> 

				<th> <label for=“name"> <font face="arial" size="4" color="green">  Capacidad del couch </font> </label> </th> 
			</tr>	

  			<% @couches.each do |couch| %>

  			<tr>
 			      <td>  <label for=“localidad"> <font face="arial" size="3" color="black"> <%= couch.name %> </font> </label></td>

 			      <td>  <label for=“localidad"> <font face="arial" size="3" color="black"> <%= couch.description %> </font> </label></td>

 			      <td>  <label for=“localidad"> <font face="arial" size="3" color="black"> <%= couch.capacidad %> </font> </label></td>

 			      
                    <td> <% if current_user.premium == true %>
                     <% if !current_user.admin? %>
                     <P style="COLOR: #000000; BACKGROUND-COLOR: #F7FE2E">PREMIUM</P> 
                     <% end %>
                  <% end %>  </td> 



 			      <td> <label for=“name"> <font face="arial" size="3" color="black">  <%= link_to "Editar",edit_couch_path(couch) %> </font> </label></td>

 			      <td> <label for=“name"> <font face="arial" size="3" color="black"> <p> <%= link_to "Eliminar", couch_path(couch), method: :delete, data: { confirm: 'Esta seguro de eliminar la publicacion?' } %> </p>
 			</tr>

                 

     <% end %>
		</table>

		<p>
			<a class="btn btn-primary btn-lg" href="/welcome/index" role=“button"> Volver </a>
		</p> 


	</div>
	
</div>

app/views/couches/new.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<label for=“name"> <font face="arial" size="5" color="green"> Publica tu couch  </font> </label>
	
	<%= form_for(@couch) do |f| %> 
      
       
       <%= f.collection_select(:tipocouch_id, Tipocouch.all, :id, :name) %>
       
        <p>
		</p>
		
		<%= f.label :name, 'Ingrese nombre' %>
		<%= f.text_field :name %> <br>
		<p>
		</p>
		
		<%= f.label :description, 'Ingrese una breve descripcion de tu couch' %>
		<%= f.text_field :description %> <br>
        <p>
		</p>

		<%= f.label :localidad, 'Ingrese localidad' %>
		<%= f.text_field :localidad %> <br>	

		<%= f.label :capacidad, 'Ingrese cantidad' %>
		<%= f.text_field :capacidad %> <br>

		<%= f.label :imageurl, 'Ingrese la imagen de tu couch(url)' %>
		<%= f.text_field :imageurl %> <br>
<p>
		</p>	
		<%= f.submit 'Guardar Couch' %>

    <% end %>
 

		<p>

			<p> <%= link_to "Volver", href="/couches/index" %> </p>

		</p> 


	</div>
	
</div>

app/views/couches/show.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<td><P ALIGN=right>
                   <a class="btn btn-primary btn-lg" href="/couches/new" role=“button"> Conviértete en anfitrión </a>
         <P ALIGN=left>         
		<label for=“name"> <font face="arial" size="5" color="green"> A continuacion se encuentra el detalle del couch seleccionado  </font> </label> 

	
		<p>

		</p>  
  	
  		<table class="table">
  			
 			<tr>
 				
				<th> <label for=“name"> <font face="arial" size="4" color="green">  Descripcion del couch </font> </label> </th>
				
				<th> <label for=“name"> <font face="arial" size="4" color="green">  Nombre del couch </font> </label> </th>

				<th> <label for=“name"> <font face="arial" size="4" color="green">  Localidad </font> </label> </th>

				<th> <label for=“name"> <font face="arial" size="4" color="green">  Capacidad </font> </label> </th>

				<th> <label for=“name"> <font face="arial" size="4" color="green">  Usuario al que pertenece </font> </label> </th>
			</tr>
                
                   <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= @couch.description %> </font> </label></td>
		           
		           <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= @couch.name %> </font> </label></td>

		           <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= @couch.localidad %> </font> </label></td>

		           <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= @couch.capacidad %> </font> </label></td>

		           <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= @user.email %> </font> </label></td>
		                   
			

		</table>


		<p>
			<a class="btn btn-primary btn-lg" href="/couches/index" role=“button"> Volver </a>
		</p> 


	</div>
	
</div>

app/views/couches/update.html.erb
<h1>Couches#update</h1>
<p>Find me in app/views/couches/update.html.erb</p>

app/views/counts/create.html.erb
<h1>Counts#create</h1>
<p>Find me in app/views/counts/create.html.erb</p>

app/views/counts/destroy.html.erb
<h1>Counts#destroy</h1>
<p>Find me in app/views/counts/destroy.html.erb</p>

app/views/counts/edit.html.erb
<h1>Counts#edit</h1>
<p>Find me in app/views/counts/edit.html.erb</p>

app/views/counts/index.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<label for="name"> <font face="arial" size="5" color="green"> Ingresa tus datos  </font> </label>
	
	  
	<form action="demo_form.asp">

			
               Ingrese su numero de tarjeta: <input type="text" name="usrname" minlength="16" maxlength="16" ><br>

               Ingrese su codigo de tarjeta: <input type="text" name="usrname" minlength="3" maxlength="3"><br>
        
               Ingrese la fecha de vencimiento de la tarjeta
		      <input type="date" id="fecha_venc" name="fecha_ven" required>
            
                    
                    <% if current_user.premium == false %>
                      <% current_user.premium= true %>
                      <% current_user.save %>


                    <% end %>
                  

                 <input type="submit" value="Enviar">
			          
              
           </form> 
   
 

		<p>

			<p> <%= link_to "Volver", href="/couches/index" %> </p>

		</p> 


	</div>
	
</div>

app/views/counts/show.html.erb
<h1>Counts#show</h1>
<p>Find me in app/views/counts/show.html.erb</p>

app/views/counts/update.html.erb
<h1>Counts#update</h1>
<p>Find me in app/views/counts/update.html.erb</p>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/ganancias.html.erb
<div class="container master-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      
      <div class="tab-content">
        
          <div class="panel panel-primary">
            <div class="panel-body">
              
              <div class="col-md-4">

                <%= form_tag "/reports/ganancias" do %>
                  <label> Indicar la fecha inicial </label> </br>
                  <%= text_field_tag :f_inicio, "",type: 'date' %></br>

                  <label> Indicar la fecha final </label> </br>
                  <%= text_field_tag :f_fin,"" ,type: 'date' %> </br>

                  <%= submit_tag 'Buscar' %>
                <% end %>

				
              </div>

              <div class="col-md-8 con_separador">
                <%if @usuarios.nil?%>
                  <h3>Aquí se mostrarán los resultados de su búsqueda.</h3>
                <%else%>
                  <%if  @usuarios.blank?%>
                    <h3>No hay resultados para su búsqueda</h3>
                  <%else%>
                    <table class="table">
                      <tr>
                        <th>Nombre y apellido</th>
                        <th>Fecha de creación</th>
                      </tr>
                      <% @usuarios.all.each do |u| %>
                      <tr>
                        <td><%=u.name%> <%=u.lastname%></td>
                        <td><%=u.created_at.strftime("%d/%m/%y a las %T")%></td>
                      </tr>
                      <%end%>
                      <tr>
                        <th>Ganancias totales</td>
                        <th><%=@total%></th>
                      </tr>
                    </table>
                  <%end%> 
                <%end %>
              </div>

            </div>
          </div>
        </div>

    </div>
  </div>
</div>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/reports/new.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<label for="name"> <font face="arial" size="5" color="green"> Crear un reporte </font> </label>

	<%= form_for(@report) do |f| %>

		<% if @report.errors.any? %>
  			<div id="error_explanation">
    			<h2><%= pluralize(@report.errors.count, "error") %> No se ha guardado</h2>
    			<ul>
    				<% @report.errors.full_messages.each do |msg| %>
      					<li><%= msg %></li>
    				<% end %>
    			</ul>
  			</div>
		<% end %>

		<p>
			<label> Indicar la fecha inicial </label> </br>
   			<%= f.text_field :f_inicio, type: 'date' %></br>

  			<label> Indicar la fecha de vuelta </label> </br>
  			<%= f.text_field :f_fin, type: 'date' %> </br>
		</p>
		
		<%= f.submit 'Guardar' %>

    <% end %>
 

		<p>

			<p> <%= link_to "Volver", href="/welcome/index" %> </p>

		</p> 


	</div>
	
</div> 

app/views/reports/registrados.html.erb
<div class="container master-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      
      <div class="tab-content">
        
          <div class="panel panel-primary">
            <div class="panel-body">
              
              <div class="col-md-4">

                <%= form_tag "/reports/registrados" do %>
                  <label> Indicar la fecha inicial </label> </br>
                  <%= text_field_tag :f_inicio, "",type: 'date' %></br>

                  <label> Indicar la fecha final </label> </br>
                  <%= text_field_tag :f_fin,"" ,type: 'date' %> </br>

                  <%= submit_tag 'Buscar' %>
                <% end %>

              </div>

              <div class="col-md-8 con_separador">
                <%if @usuarios.nil?%>
                  <h3>Aquí se mostrarán los resultados de su búsqueda.</h3>
                <%else%>
                  <%if  @usuarios.blank?%>
                    <h3>No hay resultados para su búsqueda</h3>
                  <%else%>
                    <table class="table">
                      <tr>
                        <th>Nombre y apellido</th>
                        <th>Fecha de creación</th>
                      </tr>
                      <% @usuarios.all.each do |u| %>
                      <tr>
                        <td><%=u.name%> <%=u.lastname%></td>
                        <td><%=u.created_at.strftime("%d/%m/%y a las %T")%></td>
                      </tr>
                      <%end%>
                      <tr>
                        <th>Total de usuarios registrados</td>
                        <th><%=@usuarios.length%></th>
                      </tr>
                    </table>
                  <%end%> 
                <%end %>
              </div>

            </div>
          </div>
        </div>

    </div>
  </div>
</div>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/reserves/create.html.erb
<h1>Reserves#create</h1>
<p>Find me in app/views/reserves/create.html.erb</p>

app/views/reserves/destroy.html.erb
<h1>Reserves#destroy</h1>
<p>Find me in app/views/reserves/destroy.html.erb</p>

app/views/reserves/edit.html.erb
<h1>Reserves#edit</h1>
<p>Find me in app/views/reserves/edit.html.erb</p>

app/views/reserves/index.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<label for=“name"> <font face="arial" size="5" color="green"> Solicitudes pendientes </font> </label>
	
		<p>

		</p>  
  	
  		<table class="table">

 			<tr>
 				
				<th> <label for=“name"> <font face="arial" size="4" color="green"> Nombre de couch </font> </label> </th>
				<th> <label for=“name"> <font face="arial" size="4" color="green"> Fecha de llegada </font> </label> </th>
				<th> <label for=“name"> <font face="arial" size="4" color="green"> Fecha de salida </font> </label> </th>
			</tr>

			  <% @reserve.each do |r| %>
                 

				<tr> 
					
                    <td>  <label for=“name"> <font face=" <td>  <label for=“name"> <font face="arial" size="3" color="black"> <%= r.name %> </font> </label></td>     
                    				
					<td> <label for=“name"> <font face="arial" size="3" color="black"> <%= r.fechaini %> </font> </label></td>

					<td> <label for=“name"> <font face="arial" size="3" color="black"> <%= r.fechafin %> </font> </label></td>

					<td> <label for=“name"> <font face="arial" size="3" color="black"> <p> <%= link_to "Aceptar", reserf_path(id: r.id), method: :save, data: { confirm: 'Esta seguro que quiere aceptar la reserva?' } %> </p> 
                     
					<td> <label for=“name"> <font face="arial" size="3" color="black"> <p> <%= link_to "Rechazar", reserf_path(r), method: :delete, data: { confirm: 'Esta seguro que quiere rechazar la reserva?' } %> </p> 

				</tr> 
	        
			<% end %>

		</table>

		<p>
			<a class="btn btn-primary btn-lg" href="/welcome/index" role=“button"> Volver </a>
		</p> 


	</div>
	
</div> 

app/views/reserves/new.html.erb
<%= form_for @reserve do |f| %>   
   <label> Indicar la fecha de ida </label> </br>
   <%= f.text_field :fechaini, type: 'date' %></br>
   
   <label> Indicar la fecha de vuelta </label> </br>
   <%= f.text_field :fechafin, type: 'date' %> </br>

   <%= f.hidden_field :couch_id %>
   
   <input type="submit" value="Enviar" />
<% end %>

app/views/tipocouches/index.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-lg-10">

	<div class="jumbotron"> 
		<label for="name"> <font face="arial" size="5" color="green"> A continuación se encuentra el listado de los tipos de couch existentes: </font> </label>
		<p>

		</p>  
  		<table class="table">

 			<tr>
 				<th> <label for="name"> <font face="arial" size="4" color="green"> ID </font> </label> </th>
				<th> <label for="name"> <font face="arial" size="4" color="green"> Tipo de Couch </font> </label> </th>
				<th> <label for="name"> <font face="arial" size="4" color="green"> Descripción  </font> </label> </th>
				</tr>

			<% @tipocouches.each do |tipocouch| %>

				<tr> 
	
					<td> <label for=“name"> <font face="arial" size="3" color="black"> <%= tipocouch.id %> </font> </label> </td>
					<td> <label for=“name"> <font face="arial" size="3" color="black"> <%= tipocouch.name %> </font> </label> </td>
					<td> <label for=“name"> <font face="arial" size="3" color="black"> <%= tipocouch.description %> </font> </label>
					</td>
					<td> <label for=“name"> <font face="arial" size="3" color="black">  <%= link_to "Editar",edit_tipocouch_path(tipocouch) %> </font> </label></td>
					<td> <label for=“name"> <font face="arial" size="3" color="black"> <p> <%= link_to "Eliminar", tipocouch_path(tipocouch), method: :delete, data: { confirm: 'Esta seguro de eliminar la categoría?' } %> </p> 


				</tr> 
	
			<% end %>

		</table>
		<p>
			<a class="btn btn-primary btn-lg" href="/welcome/index" role=“button"> Volver </a>
		</p> 
	</div>	
</div>