config/routes.rb
Rails.application.routes.draw do

  get 'reports/show'

  get 'reports/index'

  get 'reports/new'

  get 'reports/edit'

  get 'reports/create'

  get 'reports/update'

  get 'reports/destroy'

  get 'reports/registrados'

  get 'reports/ganancias'

  get 'counts/index'

  get 'counts/show'

  get 'counts/new'

  get 'counts/edit'

  get 'counts/create'

  get 'counts/update'

  get 'counts/destroy'

  get 'couches/index'

  get 'couches/show'

  get 'couches/new'

  get 'couches/edit'

  get 'couches/create'

  get 'couches/update'

  get 'couches/destroy'

  get 'reserves/index'

  get 'reserves/show'

  get 'reserves/new'

  get 'reserves/edit'

  get 'reserves/create'

  get 'reserves/update'

  get 'reserves/destroy'

  get 'posters/show'

  

  resources :tipocouches
  resources :reserves
  resources :couches do
   get 'mis_couches', on: :collection 
  end
  resources :counts

  devise_for :users
  get 'welcome/index'

   root 'welcome#index'

end

app/models/couch.rb
class Couch < ActiveRecord::Base
	validates_presence_of :name		
	validates_presence_of :description		
	validates_presence_of :imageurl		
	validates_presence_of :tipocouch_id
	validates_presence_of :capacidad		
	validates_presence_of :localidad		

	belongs_to :tipocouch
	belongs_to :user
	belongs_to :count
	has_many :reserves
end

app/models/count.rb
class Count < ActiveRecord::Base

	validates_presence_of :dni 
	validates_presence_of :numtarj 
	validates_presence_of :venc 
	validates_presence_of :cod
	
	belongs_to :user
	has_many :couches
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
	validates_presence_of :name	
	validates_presence_of :fechaini
	validates_presence_of :fechafin
	validates_uniqueness_of :fechafin	
	
	validates_presence_of :couch_id
	
	belongs_to :couch
	belongs_to :user

	scope :confirmed, -> { where(confirmed: true) }	
end

app/models/tipocouch.rb
class Tipocouch < ActiveRecord::Base
	#attr_accessible  :name
	#sattr_accessible  :description
	validates_presence_of :name
	validates_uniqueness_of :name
	#default_scope -> {order("id_at_desc")}
	validates :name, presence: true, length: { minimum: 4 }
	has_many :couches
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	

	validates :name, presence: true, length: { minimum: 3 }
	validates :lastname, presence: true, length: { minimum: 3 }
	validates :provincia, presence: true, length: { minimum: 3 }
	validates :localidad, presence: true, length: { minimum: 3 }
  #validates :genero, presence: true

	validates :dni, presence: true, uniqueness: true, length: {is: 8}
	validates_numericality_of :dni, :message => "Debe ingresar numeros"



  has_many :couches
  has_many :counts

  has_many :reserves
  end

app/controllers/couches_controller.rb
class CouchesController < ApplicationController
 before_action :get_couch, only: [:edit, :update, :destroy]

  def get_couch
    @couch = Couch.find(params[:id])
  end

  def index
    @couch= Couch.all
  end

  def mis_couches
    @couches = current_user.couches
    current_user.premium = false
  end 

  def show    
    @couch = Couch.find(params[:id])
    @user = @couch.user
  end

  def new
    @couch = Couch.new
    @c = Couch.all 
    @t = Tipocouch.all  
    
  end

  def edit
  end

  def create
    @couch = Couch.new(params.require(:couch).permit(:name, :description, :imageurl, :localidad , :capacidad ,:tipocouch_id)) 
    @couch.user = current_user
    @couch.save

    redirect_to couches_path
  end

  def update
    @couch.update_attributes(params.require(:couch).permit(:name, :description, :imageurl, :tipocouch_id , :capacidad , :localidad))
     redirect_to couches_path
  end

  def destroy
    @couch.destroy
    redirect_to couches_path
  end
  

end

app/controllers/counts_controller.rb
class CountsController < ApplicationController
  before_action :get_count, only: [:edit, :update, :destroy]

  def get_count
    @count = Count.find(params[:id])
  end

  def index
    @count= Count.all
     @soy_premium=false
  end

  def show    
    @count = Count.find(params[:id])
    @user = @couch.user
  end

  def new
    @count = Count.new
    
        
  end

  def edit
  end

  def create
    @count = Count.new(params.require(:count).permit(:dni, :numtarj, :venc, :cod)) 
    @count.user = current_user
    @count.save

    redirect_to counts_path
  end

  def update
    @count.update_attributes(params.require(:count).permit(:dni, :numtarj, :venc, :cod))
     redirect_to counts_path
  end

  def destroy
    @count.destroy
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  
  def show
  	@estoy_en_vista=true
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def registrados
    @report = Report.all
    fe_ini=params[:fecha_inicio]
    fe_fin=params[:fecha_fin]
    @usuarios= User.where("created_at > ? AND  created_at < ?", fe_ini, fe_fin).order("created_at")
  end

  def ganancias
    @report = Report.all
    @usuarios = User.all
    #@usuarios= User.where("created_at > ? AND  created_at < ?", f_inicio, f_fin).order("created_at")
    @usuarios.each do |u|
      @total = @total + u.precio_premium
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couches_helper.rb
module CouchesHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/tipocouches_helper.rb
module TipocouchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	
	<div class="col-md-8 col-xs-8">
		<%= link_to root_path do %>
			<%= image_tag "logochiqui.png", title:"CouchInn", class:"img-responsive" %>
		<% end %>
		<% if !@estoy_en_vista %>
			<%= link_to "Acerca de CouchInn", posters_show_path %>
			<%@estoy_en_vista= false%>
		<% end %>
	</div>
	
	<div class="col-md-4 col-xs-4 text-center" style="text-align-center">
		
		<% if user_signed_in? %>
			<%= link_to "Editar mi cuenta",edit_user_registration_path %>
			<%= link_to "Cerrar Sesión", destroy_user_session_path, method:'delete' , class:'btn btn-default' %>
		<% else %>
			<%= link_to "Iniciar Sesión", new_user_session_path , class:'btn btn-default' %>
			<%= link_to "Registrarse","/users/sign_up", class:'btn btn-default'%>
		<% end %>		

	</div>

</nav>

app/views/layouts/_lateral.html.erb
<div class="col-md-2 col-xs-4 list-group">

	<% if user_signed_in? %>

		<% if current_user.admin? %>

			<p>
				Menú administrador:
			</p>
	 
			<p> <%= link_to "Ver listado de los tipos de Couches", tipocouches_path %> </p>
			<p> <%= link_to "Dar de alta un tipo de Couch", new_tipocouch_path %> </p>
			<p> <%= link_to "Ver reportes de ganancias",reports_ganancias_path %> </p>
			<p> <%= link_to "Ver reportes de usuarios",reports_registrados_path %> </p>
			
			<p>
				Menú usuario:
			</p>

			<p> <%= link_to "Ver mis Couches",mis_couches_couches_path %> </p>
			<p> <%= link_to "Ver lista de Couches",couches_index_path %> </p>
			<p> <%= link_to "Reservas",reserves_index_path %> </p>
			<p> <%= link_to "Pasar mi cuenta a premium ",counts_new_path %> </p>
			<p> <%= link_to "Ver mis Couches",mis_couches_couches_path %> </p>

		<% else %>

			<p> <%= link_to "Ver mis Couches",mis_couches_couches_path %> </p>
			<p> <%= link_to "Ver lista de Couches",couches_index_path %> </p>
			<p> <%= link_to "Reservas",reserves_index_path %> </p>
			<p> <%= link_to "Pasar mi cuenta a premium ",counts_new_path %> </p>            
			<p> <%= link_to "Ver mis Couches",mis_couches_couches_path %> </p>

		<% end %>
	 
	<% end %>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CouchInn</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>
	<%= render "layouts/lateral" %>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>